Repository BHoM/DIALux_Toolkit, pull requests merged in 2020-06, with the labels that each got.

#49 Update referencing and post build
  DIALux_Adapter/DIALux_Adapter.csproj
  DIALux_Engine/DIALux_Engine.csproj
  DIALux_oM/DIALux_oM.csproj
Labels: type:external-api-changes

#54 Update namespace
  DIALux_Adapter/CRUD/Create.cs
  DIALux_Adapter/CRUD/Read.cs
  DIALux_Engine/Convert/Environment/Opening.cs
  DIALux_Engine/Convert/Environment/OpeningType.cs
  DIALux_Engine/Convert/Environment/Space.cs
  DIALux_Engine/Convert/Geometry/Point.cs
  DIALux_Engine/Versioning_32.json
  DIALux_oM/StfFile/Furnishing.cs
  DIALux_oM/StfFile/Luminaire.cs
  DIALux_oM/StfFile/LuminaireType.cs
  DIALux_oM/StfFile/Project.cs
  DIALux_oM/StfFile/Room.cs
  DIALux_oM/StfFile/StfFile.cs
  DIALux_oM/StfFile/Structure.cs
  DIALux_oM/StfFile/Version.cs
  DIALux_oM/Versioning_32.json
Labels: type:compliance

#55 Fix pull openings
  DIALux_Engine/Convert/Environment/Opening.cs
  DIALux_Engine/Convert/Environment/Space.cs
Labels: type:bug
